name: Core
version: '1.0-SNAPSHOT'
main: net.partmc.core.Core
api-version: '1.20'

commands:
  rtp:
    description: Random Teleport Command
    usage: /<command>
  warp:
    description: Teleports to a saved warp.
    usage: /warp <warpName>
  setwarp:
      description: Sets a warp at your location.
      usage: /setwarp <warpName>
      permission: partmc.setwarp